Repository Tap30/web-components, pull requests merged in 2025-04, with the labels that each got.

#403 ci(workflows): add update-snapshots workflow
  .github/workflows/update-snapshots.yml
Labels: bugfix, automation

#427 chore(ci): move docs deployment job to the end of release workflow
  .github/workflows/deploy.yml
  .github/workflows/release.yml
Labels: automation, chore/cleanup

#441 chore(ci): opt-in changesets publishing and versioning mechanism
  .changeset/shiny-cloths-say.md
  .github/workflows/development.yml
  .github/workflows/release.yml
  package.json
Labels: automation, chore/cleanup

#462 feat(web-components): develop discount-card component
  .changeset/stale-olives-sink.md
  packages/react-components/src/DiscountCard/DiscountCard.ts
  packages/react-components/src/DiscountCard/index.ts
  packages/react-components/src/index.ts
  packages/web-components/src/discount-card/constants.ts
  packages/web-components/src/discount-card/discount-card.style.ts
  packages/web-components/src/discount-card/discount-card.test.ts
  packages/web-components/src/discount-card/discount-card.ts
  packages/web-components/src/discount-card/element.ts
  packages/web-components/src/discount-card/index.ts
  packages/web-components/src/index.ts
Labels: feature, design-system, package: web-components, package:react-components
