Repository Tap30/web-components, pull requests merged in 2025-01, with the labels that each got.

#321 feat(snackbar): add snackbar component
  packages/web-components/src/snackbar/constants.ts
  packages/web-components/src/snackbar/events.ts
  packages/web-components/src/snackbar/icons.ts
  packages/web-components/src/snackbar/index.ts
  packages/web-components/src/snackbar/snackbar.style.ts
  packages/web-components/src/snackbar/snackbar.ts
Labels: feature

#338 docs: update components docs
  .gitignore
  docs/.vitepress/config.ts
  docs/.vitepress/nav.ts
  docs/.vitepress/sidebar.ts
  docs/.vitepress/theme/custom.css
  docs/.vitepress/theme/index.ts
  docs/components/[component].md
  docs/components/[component].paths.ts
  docs/components/doc-guideline-card/doc-guideline-card.style.ts
  docs/components/doc-guideline-card/doc-guideline-card.ts
  docs/components/doc-guideline-card/index.ts
  docs/components/doc-guideline-section/doc-guideline-section.style.ts
  docs/components/doc-guideline-section/doc-guideline-section.ts
  docs/components/doc-guideline-section/index.ts
  docs/components/doc-row/doc-row.style.ts
  docs/components/doc-row/doc-row.ts
  docs/components/doc-row/index.ts
  docs/components/index.ts
  docs/design/components/bottom-sheet.md
  docs/design/guidelines.md
  docs/dev/components/[component].md
  docs/dev/components/[component].paths.ts
  docs/dev/components/elements-config.json
  docs/dev/getting-started.md
  docs/dev/references/[reference].md
  docs/dev/references/[reference].paths.ts
  docs/index.md
  docs/internals/utils/tabulateData.ts
  docs/sidebar.ts
  docs/social-links.ts
  docs/utils/getColorTokensReferenceContent.ts
  docs/utils/getComponentsTokensReferenceContent.ts
  docs/utils/getCssPartsReferenceContent.ts
  docs/utils/getRadiusTokensReferenceContent.ts
  docs/utils/getSpacingTokensReferenceContent.ts
  docs/utils/getStrokeTokensReferenceContent.ts
  docs/utils/getTypographyTokensReferenceContent.ts
  internals/doc-helpers/schema.json
  internals/doc-helpers/types.ts
  package.json
  packages/react-components/src/TextArea.ts
  packages/web-components/src/bottom-navigation/index.ts
  packages/web-components/src/bottom-sheet/index.ts
  packages/web-components/src/chip-group/index.ts
  packages/web-components/src/chip/index.ts
  packages/web-components/src/modal/index.ts
  packages/web-components/src/notice/index.ts
  packages/web-components/src/pinwheel-group/index.ts
  packages/web-components/src/pinwheel/index.ts
  packages/web-components/src/segmented-view/index.ts
  packages/web-components/src/snackbar/index.ts
  packages/web-components/src/tooltip/index.ts
  scripts/generate-docs-metadata.ts
  tsconfig.json
Labels: docs

#352 chore(ci): introduce ci workflows
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/workflows/development.yml
  .github/workflows/npm-publish.yml
  package.json
  packages/react-components/scripts/generate.ts
  packages/react-components/src/index.ts
  playground/package.json
  pnpm-lock.yaml
  tsconfig.json
  types/@tapsioss/icons.ts
Labels: automation, chore/cleanup, priority:medium
